### ISSUE TITLE
WMS-LAndskapsdata: Getfeatureinfo

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/ninMapfileCreator#2]
LA-I-A har fungerende Getfeatureinfo /retunerer 'code' på lagets aktulle barn, samt 'name'. Ønsker samme funksjonalitet for alle wms-lag.

**Comment by bjornreppen** [comment]
Fikset i https://github.com/Artsdatabanken/ninMapfileCreator/commit/1eef98caae04d7f74d3a2a7721b8d7e4a425a662  -  klar til test
