### ISSUE TITLE
Kartprojeksjon i mapfile

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/ninMapfileCreator#5]
Støtte for ulike kartprojeksjoner må legges rett inn i mapfile (i følge @steinho)

https://mapserver.org/mapfile/projection.html 

Foreslår at vi legger samme "liste" som NIBIO:

'Projeksjonar
UTM 31-36, EUREF89
Geografiske koordinatar, EUREF89

WMS-tenesta støtter også UTM og geografiske
koordinatar i WGS84, samt Web Mercator i WGS84.'

**Comment by steinho** [comment]
map - projections er å se på som output projections - en liste over de vi støtte
layer projection er en preker på kilde projection - kun en
m.a.o. i map elementet kan det stå ala

PROJECTION
   "init=epsg:26915"
   "init=epsg:26916"
osv...
END

men de riktige kodene
